apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-slrc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0011-tenant/tkrw-pr712-0075-0011-app/devfile-sample-slrc@sha256:4be0ef8d4c4199cd830aa945931ae5ebbc439e6fa19c6cbeaecd32a2c24b5756
        name: my-nodejs
        resources: {}
status: {}
